version: '2'
volumes:
    sense-data:
    dashboard-data:
    curtain-data:
services:
  influxdb:
    restart: always
    image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
    volumes:
      - 'sense-data:/var/lib/influxdb'
  dashboard:
    image: balenablocks/dashboard
    restart: always
    volumes:
        - 'dashboard-data:/data'
    ports: 
      - "81:80"
  sensor:
    build: ./sensor
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.supervisor-api: '1'
    expose:
      - '7575'
    environment:
      RAW_VALUES: '0'
      COLLAPSE_FIELDS: '1'
  connector:
    image: balenablocks/connector
    restart: always
    labels:
      io.balena.features.balena-api: '1'
    privileged: true
    environment:
      HTTP_PUSH_URL: 'http://curtain-dashboard/api/sensor-data'
    ports:
      - "8080"
  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"
    restart: always
  motor-driver:
    build: ./motor-driver
    privileged: true
    ports: 
      - '8070'
  curtain-dashboard:
    build: ./curtain-dashboard
    environment:
      MOTORS_URL: 'http://motor-driver:8070'
    volumes:
      - 'curtain-data:/usr/src/app/data'
    ports:
      - "80"